server:
  port: 8100
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/authDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: root
    #    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8100/oauth/check_token
#    client:
#      client-id: bigcart
#      client-secret: pin
#      resource-ids: bigcart

logging:
  level:
    org:
      hibernate:
        type: trace
# -------------------------Zuul----------------------------
zuul:
  #ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    UserManagement-Service:
      url: http://localhost:9988
    products-service:
      url: http://localhost:8001
      service-id: products
    orders-service:
      url: http://localhost:8000
    notifications-service:
      url: http://localhost:8006

management:
  endpoints:
    web:
      exposure:
        include: '*'


  #server:
#  port: 8100
#spring:
#  datasource:
#    #url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:3306/authDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#
#    username: root
#    #    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
##security:
##  oauth2:
##    resource:
##      token-info-uri: http://localhost:8100/oauth/check_token
##    client:
##      client-id: bigcart
##      client-secret: pin
#
#
#
#
#
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
## -------------------------Zuul----------------------------
#zuul:
#  sensitiveHeaders: Cookie,Set-Cookie
#  #ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  routes:
#    ignoredHeaders:
#      - authorization
#    products-service:
#      path: /products/*
#      url: http://localhost:8001
#      serviceId: products-service
#    api-gateway-service:
#      path: /oauth/**
#      url: http://localhost:8100
#      serviceId: api-gateway-service
#  add-proxy-headers: true
##    UserManagement-Service:
##      url: http://localhost:9988
##    products-service:
##      url: http://localhost:8001
##    orders-service:
##      url: http://localhost:8000
##    notifications-service:
##      url: http://localhost:8006
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#      type: trace
### -------------------------Zuul----------------------------
#
###zuul:
###  routes:
###    products-service:
###      url: http://localhost:8001
###      service-id: products-service
###      path: products-service/**
##
##
##zuul:
###  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
##  sensitiveHeaders: Cookie,Set-Cookie
##  routes:
##    products-service:
##      path: /products/*
##      url: http://localhost:8001
##      serviceId: products-service
##    api-gateway-service:
##      path: /oauth/**
##      url: http://localhost:8100
##      serviceId: api-gateway-service
##
##
###    products-service:
###      url: http://localhost:8001
###      service-id: products-service
###      path: products-service/**
###    bigcart-authentication-server:
###      path: /bigcart-authentication-server/**
###      url: http://localhost:9191/bigcart-authentication-server
###    products-service:
###      path: /products-service/**
###      url: http://localhost:8001/products-service
##
###    UserManagement-Service:
###      url: http://localhost:9988
###      serviceId: UserManagement-Service
###      path: UserManagement-Service/**
###
###    orders-service:
###      url: http://localhost:8000
###    notifications-service:
###      url: http://localhost:8006
#
